name: Deploy Kiosk Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy bot
        run: |
          cd /home/ec2-user/kiosk-bot
          git pull origin main
          npm install
          sudo systemctl restart kiosk-bot
          sudo systemctl status kiosk-bot --no-pager